# Build Settings (https://pnpm.io/settings#build-settings)
nodeOptions: "--experimental-vm-modules"
verifyDepsBeforeRun: "prompt"
onlyBuiltDependencies:
  - unrs-resolver

# https://pnpm.io/cli/run#shellemulator
shellEmulator: true
