# Build Settings (https://pnpm.io/settings#build-settings)
nodeOptions: "--experimental-vm-modules"
verifyDepsBeforeRun: "prompt"
onlyBuiltDependencies:
  - unrs-resolver

# Other Settings (https://pnpm.io/settings#other-settings)
shellEmulator: true
